### PR TITLE
[TACKLE-7] Controls - Tags and Tag Types

### PR DESCRIPTION
**Pull request by carlosthe19916**
Resolves: https://github.com/konveyor/tackle-ui/issues/101

### CODE REVIEW

**Review by mrizzi — COMMENTED** [review]
First round of testing, I found some issues:

1. when creating a `Tag`, the `Tag type` field is not mandatory and hence the `Create` button is enabled even if no tag type has been selected
2. a tag type without any tag assigned has the expanding arrow enabled
3. filter field `Name` should be named `Tag type`
4. filter field `Tag` should be named `Tags`

**Comment by carlosthe19916** [comment]
> First round of testing, I found some issues:
> 
> 1. when creating a `Tag`, the `Tag type` field is not mandatory and hence the `Create` button is enabled even if no tag type has been selected
> 2. a tag type without any tag assigned has the expanding arrow enabled
> 3. filter field `Name` should be named `Tag type`
> 4. filter field `Tag` should be named `Tags`

@mrizzi thanks for the review, here is my reply:

1. `when creating a Tag, the Tag type field is not mandatory`: solved in previous commits.
2. `a tag type without any tag assigned has the expanding arrow enabled`: I couldn't find a way to disable the "expand" button using current version of @patternfly/react-table, instead I decided to remove the "expand" button when the tagType doesn't have any tags inside. Do you agree with this approach?
Screenshot from 2021-04-16 19-30-53

3. `filter field Name should be named Tag type`: solved in previous commits.
4. `filter field Tag should be named Tags`: I don't think is the right thing to do; when we apply a filter we apply a "SINGLE" filter so we should keep "Tag" in singular rather than "Tags" in plural. e.g.
- We say "Filter by description" not "Filter by descriptions".
- We say "Filter by business service" not "Filter by business services".

In all filters we are following the singular form of words, for instance:
Screenshot from 2021-04-16 19-44-30

**Comment by mrizzi** [comment]
>     2. `a tag type without any tag assigned has the expanding arrow enabled`: I couldn't find a way to disable the "expand" button using current version of @patternfly/react-table, instead I decided to remove the "expand" button when the tagType doesn't have any tags inside. Do you agree with this approach?

Approved by UX team.

>     4. `filter field Tag should be named Tags`: I don't think is the right thing to do; when we apply a filter we apply a "SINGLE" filter so we should keep "Tag" in singular rather than "Tags" in plural. e.g.

Agreed about changing it to be `Tag name`

**Review by mrizzi — APPROVED** [review]
Tested successfully with controls backend based on https://github.com/konveyor/tackle-controls/pull/112.

Thanks a lot @carlosthe19916: this is another great contribution :+1:

**Pull request merged**
