### PR TITLE
[TACKLE-61] Manage Application Dependencies

### PR DESCRIPTION
**Pull request by carlosthe19916**
Resolves: https://github.com/konveyor/tackle-ui/issues/98
Depends on: https://github.com/konveyor/tackle-ui/pull/73

### CODE REVIEW

**Review by mrizzi — COMMENTED** [review]
The tests have been fine.
I would just ask if it's possible to add the sorting by application's name to fetched application lists to have the applications in the select menu sorted consistently with the default sort by `Name` applied in the `Application inventory` page.

**Review by mrizzi — COMMENTED** [review]
thanks for the sorting fix: it worked great.
After another round of tests with @PhilipCattanach, it has been agreed on adding in the modal the following warn message to let the user know how the dependencies modal works:
Screenshot from 2021-04-26 19-16-23
@carlosthe19916 could you do this further change please? thanks

**Comment by carlosthe19916** [comment]
> thanks for the sorting fix: it worked great.
> After another round of tests with @PhilipCattanach, it has been agreed on adding in the modal the following warn message to let the user know how the dependencies modal works:
> Screenshot from 2021-04-26 19-16-23
> @carlosthe19916 could you do this further change please? thanks

@mrizzi my last commit added the "warn message" as requested

**Review by mrizzi — COMMENTED** [review]
testing the new warning message, I got into an error situation due to infrastructure failures that generated this issue in the page
Screenshot from 2021-04-27 11-09-57

@carlosthe19916 proposed an enhancement in the application inventory backend to then fix this behavior in the UI

**Comment by carlosthe19916** [comment]
@mrizzi my last commit has replaced the way of extracting the backend error message text so you shouldn't see that behavior anymore.

**Review by mrizzi — APPROVED** [review]
Thanks a lot @carlosthe19916 for all the enhancements: everything tested successfully so far with latest changes about error message for cycle detection.
Tested successfully also with some error case like `404`, `500` and `504` and the UI managed fine the errors coming from backend.

**Pull request merged**
