### PR TITLE
[TACKLE-8] manage Application to Tag relationships

### PR DESCRIPTION
**Pull request by carlosthe19916**
Resolves: https://github.com/konveyor/tackle-ui/issues/95 , https://github.com/konveyor/tackle-ui/issues/97 , https://github.com/konveyor/tackle-ui/issues/96

- [TACKLE-8] manage Application to Tag relationships
- [TACKLE-8] Sort Application Inventory by Tag Count column
- [TACKLE-8] Application filtering by Tags

### CODE REVIEW

**Comment by carlosthe19916** [comment]
Preview of the "Create app" and "Filter by tag"

https://user-images.githubusercontent.com/2582866/116061295-fc131380-a682-11eb-9fa6-070b9847b410.mp4

**Review by mrizzi — COMMENTED** [review]
@carlosthe19916 the tests have been fine, really like this enhancement.
I've just found an odd behavior in the "inner filter" when filtering by tags: the text input box becomes smaller while typing. I hope the next video can better explain:

https://user-images.githubusercontent.com/7288588/116123585-75caf180-a6c3-11eb-89c6-2bb72071e2be.mp4

**Comment by carlosthe19916** [comment]
@mrizzi My last commit has set a static min-width of the "Tag dropdown" of 200px, this should give a better look and feel; however, this won't prevent the width to change its width in case any element of the dropdown is long enough to create a distortion. E.g. let's say we have an element in the dropdown with 500 characters and the rest of the elements have only 20 characters, then the width of the "expanded dropdown" will necessarily be automatically increased to fit the longest dropdown element, and if the user filters the dropdown making disappear the longest element then the width will be restored to the min-width value

There is nothing I can do to prevent this behavior to happen other than what I did setting the min-width to 200px.

https://user-images.githubusercontent.com/2582866/116199615-9b91de00-a737-11eb-9dce-0bdf4254f83b.mp4

**Comment by mrizzi** [comment]
> @mrizzi My last commit has set a static min-width of the "Tag dropdown" of 200px, this should give a better look and feel; however, this won't prevent the width to change its width in case any element of the dropdown is long enough to create a distortion. E.g. let's say we have an element in the dropdown with 500 characters and the rest of the elements have only 20 characters, then the width of the "expanded dropdown" will necessarily be automatically increased to fit the longest dropdown element, and if the user filters the dropdown making disappear the longest element then the width will be restored to the min-width value
> 
It makes sense to me, thanks :+1:

**Review by mrizzi — APPROVED** [review]
Latest change worked fine, thanks @carlosthe19916: it's another valuable addition to Tackle :+1:

**Pull request merged**
