### PR TITLE
[TACKLE-107] Review - enterable fields

### LINKED ISSUE #106: [TACKLE-107]Review - display only components that originate from the Assessment entity.
Doughnut chart of risks, consolidated comments and the Assessment table (questions/answers/risks).

### PR DESCRIPTION
**Pull request by carlosthe19916**
Resolves https://github.com/konveyor/tackle-ui/issues/105
resolves #106

### CODE REVIEW

**Review by mrizzi — COMMENTED** [review]
Done some tests and found the following issues/enhancements:

- `Review` button must be disabled when the selected application's assessment is *not* `Completed`
- the donut chart has some white space even if risks are 100% unknown because other risks' colour have space even if they are `0`
  Screenshot from 2021-05-19 11-07-59
- the donut chart should be bigger and closer to the left text boxes
   Screenshot from 2021-05-19 11-34-03
- `Assessment notes` box could be improved reporting:
   - one comment per line
   - each line follows the pattern `{category.title}: {category.comment}`, e.g. `Application Details: notes and comments`
   - if no comment is available for a category, then no line must be added
- `Assessment summary`:
   - missing `Category` column
   - TBD with PM and UX about using `Rank` (like in mockups) or `Risk` (like in the current implementation): hold on before implementing something about this
   - sorting by `Risk` when there's just one category (e.g. `Unknown` in [this review](https://tackle-mta-pathfinder.apps.ocp4.prod.psi.redhat.com/application-inventory/application/28/review)) changes the order even if the risk is just one and the sort should not change
   - pagination with pre-selected `50` elements per page so that all answers are shown
- `Business criticality` and `Work priority` value selectors should not allow to the `-` button to work below 1 and the `+` one above 10
- when changing and then selecting again the "original" values for both `Proposed action` and `Effort estimation`, the `Submit review` button is always enabled (while with the other fields, when restoring the original values, the `Submit review` button gets disabled)
- when changing the size of the `Comments` text box, the above components change their size as well
   Screenshot from 2021-05-19 11-44-48

**Comment by carlosthe19916** [comment]
### 1. `Review` button must be disabled when the selected application's assessment is _not_ `Completed`

Answer: `I require confirmation`:

**Current behavior**: If the user selects one application then the "Review" button is enabled; then, the user clicks on the "Review" button. If the application's assessment is not `Completed` then a "toastr" message appears indicating the user that he must complete the assessment before being able to "Review" the app.
**Suggested behavior**: If the user selects one application that has not been assessed yet then the `Review` button is disabled. From my point of view, this is not intuitive for the user as there isn't a clear way to let the user know "Why the review button is disabled" (there isn't a place where is written that in order to review we need to assess the app before)

Anyway, I'll let @PhilipCattanach make the decision of whether or not to follow the suggested approach or keep the current approach.

### 2. the donut chart has some white space even if risks are 100% unknown because other risks' colour have space even if they are 0

Answer: `Done`

Thanks, this was done with my last commit.

### 3. the donut chart should be bigger and closer to the left text boxes

Answer: `Done`

Chart's size increased from `width:230px, height:230px` to `width:250px, height:250px` and removed a space (around 20px) between the chart form and the donut chart

### 4. Assessment notes box could be improved reporting:
> one comment per line
> each line follows the pattern {category.title}: {category.comment}, e.g. Application Details: notes and comments
> if no comment is available for a category, then no line must be added

Answer: `I require confirmation`:

This is not how the mockups were defined. @PhilipCattanach could please confirm the proposed change is what you want? If you confirm it I can proceed to make the required changes.

### 5. Assessment summary
> missing Category column

Column added

> TBD with PM and UX about using Rank (like in mockups) or Risk (like in the current implementation): hold on before implementing something about this

waiting for confirmation

> sorting by Risk when there's just one category (e.g. Unknown in this review) changes the order even if the risk is just one and the sort should not change

Working on this

### 6. Business criticality and Work priority value selectors should not allow to the - button to work below 1 and the + one above 10
Answer: `Done`:

My last commit will disable the `-`, `+` if the input value is less than 1 or greater than 10; however, it won't prevent the user to manually write a value outside this range (this is how this PF component works); if the user manually writes an invalid value then he will see a red error message below the input text

### 7. when changing and then selecting again the "original" values for both Proposed action and Effort estimation, the Submit review button is always enabled (while with the other fields, when restoring the original values, the Submit review button gets disabled)

Answer: `I require confirmation`:

This seems to be a global issue in all "Select" components within a Form. The bug was reported here https://issues.redhat.com/browse/TACKLE-180 . I'd suggest fixing this bug in another PR and do it for all forms and not just for this one. Do you agree?

### 8. when changing the size of the Comments text box, the above components change their size as well

Answer: `I couldn't reproduce the bug`

I'm not sure how you were able to do that, what I see is this:
Screenshot from 2021-05-19 13-29-30

### 9. Beside the previous enhancements to current implementation, it seems like the changes for the application list page to reflect the review's values is missing.

Answer: `Working on it`

**Comment by carlosthe19916** [comment]
Update about point `#8`
### 8. when changing the size of the Comments text box, the above components change their size as well
Answer: I couldn't reproduce the bug

The issue appears when the user tries to change the size of the "TextArea" using the "arrow" located in the left bottom corner of the "TextArea".

`Working on this to see how to fix it`

**Comment by carlosthe19916** [comment]
> * `Review` button must be disabled when the selected application's assessment is _not_ `Completed`

**Done**

> * the donut chart has some white space even if risks are 100% unknown because other risks' colour have space even if they are `0`

**Done**

> * the donut chart should be bigger and closer to the left text boxes

**Done**

> * `Assessment notes` box could be improved reporting:
>   
>   * one comment per line
>   * each line follows the pattern `{category.title}: {category.comment}`, e.g. `Application Details: notes and comments`
>   * if no comment is available for a category, then no line must be added

**Done**

> * `Assessment summary`:
>   
>   * missing `Category` column
>   * TBD with PM and UX about using `Rank` (like in mockups) or `Risk` (like in the current implementation): hold on before implementing something about this
>   * sorting by `Risk` when there's just one category (e.g. `Unknown` in [this review](https://tackle-mta-pathfinder.apps.ocp4.prod.psi.redhat.com/application-inventory/application/28/review)) changes the order even if the risk is just one and the sort should not change
>   * pagination with pre-selected `50` elements per page so that all answers are shown

**Done**

Just one comment about `pagination with pre-selected 50 elements per page so that all answers are shown`: This change has been done as requested; however, I wonder why are we adding pagination to a table that will show all elements? the pagination is useless and adds no value. Anyway, the change has been done, and if the decision about `50 elements per page` changes we can open a new PR in the future.

> * `Business criticality` and `Work priority` value selectors should not allow to the `-` button to work below 1 and the `+` one above 10

**Done**

> * when changing and then selecting again the "original" values for both `Proposed action` and `Effort estimation`, the `Submit review` button is always enabled (while with the other fields, when restoring the original values, the `Submit review` button gets disabled)

As mentioned before, this is a global issue in all "Select" components within a Form. I suggest fixing this bug on another PR since this change will touch other UI pages where any form with "select" components exists.

> * when changing the size of the `Comments` text box, the above components change their size as well

**Done**

@mrizzi  please take a look to the latest changes available

**Review by mrizzi — COMMENTED** [review]
As mentioned, sorting by `Risk` after having filtered by `Risk` is not working as expecting.

**Comment by carlosthe19916** [comment]
> As mentioned, sorting by `Risk` after having filtered by `Risk` is not working as expecting.

@mrizzi Thanks for the great feedback. My last commit fixed this bug.

**Review by mrizzi — COMMENTED** [review]
@carlosthe19916 I'm sorry for not having spotted this earlier but in the mockups there's "Effort estimat**e**" and not "Effort estimat**ion**" both in the review page and in the expanded row in the application list.
Better make the page perfectly fine with the mockups to avoid issues later.

**Comment by carlosthe19916** [comment]
> @carlosthe19916 I'm sorry for not having spotted this earlier but in the mockups there's "Effort estimat**e**" and not "Effort estimat**ion**" both in the review page and in the expanded row in the application list.
> Better make the page perfectly fine with the mockups to avoid issues later.

@mrizzi Thanks for reporting this issue. For sure it is better to fix inconsistencies as soon as possible. My last commit fixed the error.

**Review by mrizzi — APPROVED** [review]
Thanks a lot @carlosthe19916, everything fine for me :+1: 
I've also tested the `Save and review` button that took me from the last section of the questionnaire into this Review page.

**Pull request merged**
